name = "starisle"
main = "src/worker/index.ts"
compatibility_date = "2024-09-09"

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "starisle"
database_id = "3bcd4a66-995d-4a64-9c57-e5a3c6d8fca4"
