// Pulls the real public data from the live starisle site and generates src/db/seed-data.sql.
// Password hashes are left as a placeholder (see scripts/hash-passwords.mjs).
import { writeFileSync, mkdirSync } from "node:fs";

const BASE = "https://forum.aiyf.org.cn/api";
const OUT = new URL("../src/db/seed-data.sql", import.meta.url).pathname;

async function get(path) {
  const r = await fetch(BASE + path);
  if (!r.ok) throw new Error(`${path}: ${r.status}`);
  return r.json();
}

mkdirSync(new URL("../public/avatars", import.meta.url).pathname, { recursive: true });
mkdirSync(new URL("../public/posters", import.meta.url).pathname, { recursive: true });
mkdirSync(new URL("../public/partners", import.meta.url).pathname, { recursive: true });

const dataUri = (v, dir, name) => {
  if (typeof v !== "string" || !v.startsWith("data:image")) return null;
  const m = v.match(/^data:image\/(\w+);base64,(.+)$/s);
  if (!m) return null;
  const ext = m[1] === "jpeg" ? "jpg" : m[1];
  const safe = String(name).replace(/[^a-zA-Z0-9_-]/g, "_");
  writeFileSync(new URL(`../public/${dir}/${safe}.${ext}`, import.meta.url).pathname, Buffer.from(m[2], "base64"));
  return `/${dir}/${safe}.${ext}`;
};

const esc = (v) => {
  if (v === null || v === undefined) return "NULL";
  if (typeof v === "number") return String(v);
  return `'${String(v).replaceAll("'", "''").replace(/[\r\n]+/g, " ")}'`;
};

const stats = await get("/stats");
const { projects } = await get("/projects");
const { courses } = await get("/courses");
const { columns } = await get("/columns");
const { members } = await get("/members");
const { mentors } = await get("/mentors");
const { domains } = await get("/domains");
const { partners } = await get("/partners");

// project detail: fetch each for gaps/stack/body/demo
const details = [];
for (const p of projects) {
  try {
    details.push(await get(`/projects/${p.slug}`));
  } catch {
    details.push({ project: p });
  }
}

const L = [];
L.push("-- generated by scripts/fetch-seed.mjs — real data harvested from the legacy site");

for (const d of domains)
  L.push(`INSERT OR IGNORE INTO domains (id,name,color) VALUES (${esc(d.id)},${esc(d.name)},${esc(d.color)});`);

// members: everyone gets the dev password placeholder, hashed in a later step
for (const m of members) {
  const avatar = dataUri(m.avatar, "avatars", m.id);
  L.push(
    `INSERT INTO members (id,username,display_name,bio,repo_url,avatar,password_hash,salt,created_at) VALUES (${m.id},${esc(m.username)},${esc(m.display_name)},${esc(m.bio)},${esc(m.repo_url)},${esc(avatar)},'__HASH__','__SALT__',${esc(m.created_at)}) ON CONFLICT(id) DO UPDATE SET avatar=excluded.avatar, bio=excluded.bio, repo_url=excluded.repo_url;`
  );
}

// demo/admin accounts (documented credentials, dev only)
L.push(
  `INSERT INTO members (username,display_name,email,bio,password_hash,salt) VALUES ('施清荃','QQSHI13','demo@starisle.local','Imported member.','__HASH__','__SALT__') ON CONFLICT(username) DO NOTHING;`
);
L.push(
  `INSERT OR IGNORE INTO members (username,display_name,email,bio,password_hash,salt,role) VALUES ('演示成员','Demo Member','member@starisle.local','Demo member account.','__HASH__','__SALT__','member');`
);

const ownerRef = (username) =>
  `COALESCE((SELECT id FROM members WHERE username=${esc(username)}), (SELECT MIN(id) FROM members))`;

for (const d of details) {
  const p = d.project ?? d;
  L.push(
    `INSERT OR IGNORE INTO projects (slug,name,tagline,body,repo_url,demo_url,domain_id,status,owner_id,created_at,updated_at) VALUES (${esc(p.slug)},${esc(p.name)},${esc(p.tagline ?? "")},${esc(p.body || p.description || "")},${esc(p.repo_url)},${esc(p.demo_url)},${esc(p.domain_id)},'approved',${ownerRef(p.owner?.username ?? "")},${esc(p.created_at)},${esc(p.updated_at ?? p.created_at)});`
  );
  const posterPath = dataUri(p.poster, "posters", p.slug);
  if (posterPath)
    L.push(`UPDATE projects SET poster_url = ${esc(posterPath)} WHERE slug = ${esc(p.slug)};`);
  for (const m of d.members ?? []) {
    const mid = `(SELECT id FROM members WHERE username=${esc(m.username)})`;
    L.push(`INSERT OR IGNORE INTO project_members (project_id,member_id,role) VALUES ((SELECT id FROM projects WHERE slug=${esc(p.slug)}),${mid},${esc(m.role ?? "member")});`);
  }
  for (const t of p.stack ?? [])
    L.push(`INSERT OR IGNORE INTO project_stacks (project_id,tag) SELECT (SELECT id FROM projects WHERE slug=${esc(p.slug)}),${esc(t)} WHERE NOT EXISTS (SELECT 1 FROM project_stacks WHERE project_id=(SELECT id FROM projects WHERE slug=${esc(p.slug)}) AND tag=${esc(t)});`);
  const ms = Array.isArray(p.milestones) ? p.milestones : [];
  ms.forEach((m, i) => {
    const text = typeof m === "string" ? m : (m.text ?? m.title ?? "");
    if (text) L.push(`INSERT OR IGNORE INTO project_milestones (project_id,text,done,sort) SELECT (SELECT id FROM projects WHERE slug=${esc(p.slug)}),${esc(text)},${m.done ? 1 : 0},${i} WHERE NOT EXISTS (SELECT 1 FROM project_milestones WHERE project_id=(SELECT id FROM projects WHERE slug=${esc(p.slug)}) AND text=${esc(text)});`);
  });
  for (const g of d.gaps ?? [])
    L.push(`INSERT INTO project_gaps (project_id,label) SELECT (SELECT id FROM projects WHERE slug=${esc(p.slug)}),${esc(g.label ?? g)} WHERE NOT EXISTS (SELECT 1 FROM project_gaps WHERE project_id=(SELECT id FROM projects WHERE slug=${esc(p.slug)}) AND label=${esc(g.label ?? g)});`);
}

for (const c of courses)
  L.push(
    `INSERT OR IGNORE INTO courses (id,slug,title,subject,track,summary,instructors,total_hours,featured,status,lesson_count) VALUES (${c.id},${esc(c.slug)},${esc(c.title)},${esc(c.subject)},${esc(c.track)},${esc(c.summary)},${esc(c.instructors)},${esc(c.total_hours)},${c.featured ? 1 : 0},'published',${c.lesson_count});`
  );

for (const c of columns)
  L.push(
    `INSERT OR IGNORE INTO columns (id,slug,column_label,title,subtitle,author,author_title,text,published_at) VALUES (${c.id},${esc(c.slug)},${esc(c.column)},${esc(c.title ?? (c.slug === 'dean-letter-2026' ? '写给少年学院 2026 届同学的一封信' : c.column))},${esc(c.subtitle ?? (c.slug === 'dean-letter-2026' ? '你们这一代，会走得比我们想象的更远' : ''))},${esc(c.author ?? "刘铁岩")},${esc(c.author_title ?? "北京中关村学院党委书记、院长 · 北京少年人工智能学院（海淀）院长")},${esc(c.text)},${esc(c.published_at ?? "2026-09-17")});`
  );

for (const m of mentors) {
  L.push(`INSERT OR IGNORE INTO mentors (id,slug,name,title,bio) VALUES (${m.id},${esc(m.slug)},${esc(m.name)},${esc(m.title)},${esc(m.bio)});`);
  for (const mc of m.courses ?? [])
    L.push(`INSERT INTO mentor_courses (mentor_id,course_title,hours,level) SELECT ${m.id},${esc(mc.title)},${esc(mc.total_hours ?? mc.hours)},${esc(mc.level)} WHERE NOT EXISTS (SELECT 1 FROM mentor_courses WHERE mentor_id=${m.id} AND course_title=${esc(mc.title)});`);
}

for (const p of partners) {
  let logo = null;
  if (p.logo_path) {
    try {
      const ext = (p.logo_path.match(/\.(\w+)(?:\?|$)/) || [,"png"])[1].toLowerCase();
      const res = await fetch(encodeURI("https://forum.aiyf.org.cn" + p.logo_path));
      if (res.ok) {
        writeFileSync(new URL(`../public/partners/${p.id}.${ext}`, import.meta.url).pathname, Buffer.from(await res.arrayBuffer()));
        logo = `/partners/${p.id}.${ext}`;
      }
    } catch { logo = null; }
  }
  L.push(`INSERT INTO partners (id,slug,name,category,website,logo_url,monogram) VALUES (${p.id},${esc(p.slug)},${esc(p.name)},${esc(p.category)},${esc(p.website)},${esc(logo)},${esc(p.monogram ?? "")}) ON CONFLICT(id) DO UPDATE SET logo_url=excluded.logo_url, website=excluded.website;`);
}

writeFileSync(OUT, L.join("\n") + "\n");
console.log(`seed-data.sql written: ${L.length} statements`);
console.log(`stats from legacy: ${JSON.stringify(stats)}`);
