// Pulls the real public data from the live starisle site and generates src/db/seed-data.sql.
// Password hashes are left as a placeholder (see scripts/hash-passwords.mjs).
import { writeFileSync } from "node:fs";

const BASE = "https://forum.aiyf.org.cn/api";
const OUT = new URL("../src/db/seed-data.sql", import.meta.url).pathname;

async function get(path) {
  const r = await fetch(BASE + path);
  if (!r.ok) throw new Error(`${path}: ${r.status}`);
  return r.json();
}

const esc = (v) => {
  if (v === null || v === undefined) return "NULL";
  if (typeof v === "number") return String(v);
  return `'${String(v).replaceAll("'", "''").replace(/[\r\n]+/g, " ")}'`;
};

const stats = await get("/stats");
const { projects } = await get("/projects");
const { courses } = await get("/courses");
const { columns } = await get("/columns");
const { members } = await get("/members");
const { mentors } = await get("/mentors");
const { domains } = await get("/domains");
const { partners } = await get("/partners");

// project detail: fetch each for gaps/stack/body/demo
const details = [];
for (const p of projects) {
  try {
    details.push(await get(`/projects/${p.slug}`));
  } catch {
    details.push({ project: p });
  }
}

const L = [];
L.push("-- generated by scripts/fetch-seed.mjs — real data harvested from the legacy site");

for (const d of domains)
  L.push(`INSERT OR IGNORE INTO domains (id,name,color) VALUES (${esc(d.id)},${esc(d.name)},${esc(d.color)});`);

// members: everyone gets the dev password placeholder, hashed in a later step
for (const m of members)
  L.push(
    `INSERT OR IGNORE INTO members (id,username,display_name,bio,repo_url,password_hash,salt,created_at) VALUES (${m.id},${esc(m.username)},${esc(m.display_name)},${esc(m.bio)},${esc(m.repo_url)},'__HASH__','__SALT__',${esc(m.created_at)});`
  );

// demo/admin accounts (documented credentials, dev only)
L.push(
  `INSERT OR IGNORE INTO members (username,display_name,email,bio,password_hash,salt,role) VALUES ('施清荃','QQSHI13','demo@starisle.local','Demo member account.','__HASH__','__SALT__','admin');`
);
L.push(
  `INSERT OR IGNORE INTO members (username,display_name,email,bio,password_hash,salt,role) VALUES ('演示成员','Demo Member','member@starisle.local','Demo member account.','__HASH__','__SALT__','member');`
);

const ownerRef = (username) =>
  `COALESCE((SELECT id FROM members WHERE username=${esc(username)}), (SELECT MIN(id) FROM members))`;

for (const d of details) {
  const p = d.project ?? d;
  L.push(
    `INSERT OR IGNORE INTO projects (slug,name,tagline,body,repo_url,demo_url,domain_id,status,owner_id,created_at,updated_at) VALUES (${esc(p.slug)},${esc(p.name)},${esc(p.tagline ?? "")},${esc(p.body || p.description || "")},${esc(p.repo_url)},${esc(p.demo_url)},${esc(p.domain_id)},'approved',${ownerRef(p.owner?.username ?? "")},${esc(p.created_at)},${esc(p.updated_at ?? p.created_at)});`
  );
  for (const m of d.members ?? []) {
    const mid = `(SELECT id FROM members WHERE username=${esc(m.username)})`;
    L.push(`INSERT OR IGNORE INTO project_members (project_id,member_id,role) VALUES ((SELECT id FROM projects WHERE slug=${esc(p.slug)}),${mid},${esc(m.role ?? "member")});`);
  }
  for (const g of d.gaps ?? [])
    L.push(`INSERT INTO project_gaps (project_id,label) SELECT (SELECT id FROM projects WHERE slug=${esc(p.slug)}),${esc(g.label ?? g)} WHERE NOT EXISTS (SELECT 1 FROM project_gaps WHERE project_id=(SELECT id FROM projects WHERE slug=${esc(p.slug)}) AND label=${esc(g.label ?? g)});`);
}

for (const c of courses)
  L.push(
    `INSERT OR IGNORE INTO courses (id,slug,title,subject,track,summary,instructors,total_hours,featured,status,lesson_count) VALUES (${c.id},${esc(c.slug)},${esc(c.title)},${esc(c.subject)},${esc(c.track)},${esc(c.summary)},${esc(c.instructors)},${esc(c.total_hours)},${c.featured ? 1 : 0},'published',${c.lesson_count});`
  );

for (const c of columns)
  L.push(
    `INSERT OR IGNORE INTO columns (id,slug,column_label,title,subtitle,author,author_title,text,published_at) VALUES (${c.id},${esc(c.slug)},${esc(c.column)},${esc(c.title ?? (c.slug === 'dean-letter-2026' ? '写给少年学院 2026 届同学的一封信' : c.column))},${esc(c.subtitle ?? (c.slug === 'dean-letter-2026' ? '你们这一代，会走得比我们想象的更远' : ''))},${esc(c.author ?? "刘铁岩")},${esc(c.author_title ?? "北京中关村学院党委书记、院长 · 北京少年人工智能学院（海淀）院长")},${esc(c.text)},${esc(c.published_at ?? "2026-09-17")});`
  );

for (const m of mentors) {
  L.push(`INSERT OR IGNORE INTO mentors (id,slug,name,title,bio) VALUES (${m.id},${esc(m.slug)},${esc(m.name)},${esc(m.title)},${esc(m.bio)});`);
  for (const mc of m.courses ?? [])
    L.push(`INSERT INTO mentor_courses (mentor_id,course_title,hours,level) SELECT ${m.id},${esc(mc.title)},${esc(mc.total_hours ?? mc.hours)},${esc(mc.level)} WHERE NOT EXISTS (SELECT 1 FROM mentor_courses WHERE mentor_id=${m.id} AND course_title=${esc(mc.title)});`);
}

for (const p of partners)
  L.push(`INSERT OR IGNORE INTO partners (id,slug,name,category,website,monogram) VALUES (${p.id},${esc(p.slug)},${esc(p.name)},${esc(p.category)},${esc(p.website)},${esc(p.monogram ?? "")});`);

writeFileSync(OUT, L.join("\n") + "\n");
console.log(`seed-data.sql written: ${L.length} statements`);
console.log(`stats from legacy: ${JSON.stringify(stats)}`);
